### PR TITLE
Test openjpeg

### PR DESCRIPTION
**Pull request by ocefpaf**
I could not get this to work locally but leave a PR open here anyways.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Both `Linux` and `OS X` are failing with:

```shell
/feedstock_root/build_artefacts/work/grib_api-1.16.0-Source/src/grib_openjpeg_encoding.c:164:2: error: too few arguments to function ‘opj_decode’
  image = opj_decode(dinfo, cio);
  ^
In file included from /feedstock_root/build_artefacts/work/grib_api-1.16.0-Source/src/grib_openjpeg_encoding.c:14:0:
/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/include/openjpeg-2.1/openjpeg.h:1303:31: note: declared here
 OPJ_API OPJ_BOOL OPJ_CALLCONV opj_decode(   opj_codec_t *p_decompressor,
                               ^
make[2]: *** [src/CMakeFiles/grib_api.dir/grib_openjpeg_encoding.c.o] Error 1
make[1]: *** [src/CMakeFiles/grib_api.dir/all] Error 2
make: *** [all] Error 2
Command failed: /bin/bash -x -e /feedstock_root/build_artefacts/work/grib_api-1.16.0-Source/conda_build.sh
```

**Comment by kynan** [comment]
This should be fixed in the latest grib_api release.

**Comment by ocefpaf** [comment]
> This should be fixed in the latest grib_api release.

Do you mean 1.19.0 or an unrelease version? I could not make it work with 1.19.0 but I am not sure I am doing the right thing with `cmake` here.

**Comment by kynan** [comment]
CMake output looks legit, I'll double check.

**Comment by kmuehlbauer** [comment]
ECMWF states that they support only to [openjpeg 1.5.2](https://software.ecmwf.int/wiki/display/GRIB/GRIB+API+Autotools+installation).

The openjpeg ABI changed in version 2 (http://www.openjpeg.org/abi-check/headers_diff/openjpeg/1.5.2/2.0/diff.html). It seems, that something isn't working properly in the `grib_api`-coding applying to openjpeg version2.

**Comment by ocefpaf** [comment]
The question I never asked is this: do you want to use `openjpeg` or are you guys fine with `jasper`?

**Comment by kmuehlbauer** [comment]
@ocefpaf It looks like both can be compiled in (https://software.ecmwf.int/wiki/display/GRIB/GRIB+API+Frequently+Asked+Questions+FAQ, see "Special undocumented environment variables").

Before we can use latest `openjpeg` (>v2), there need to be the according changes upstream.

**Comment by ocefpaf** [comment]
So the question changes to: do we want both? I am not an `ecmwf_grib` expert user to know what path is preferred here. I was just testing with `openjepg` because `jasper` seems old and unsupported. However, sometimes old and unsupported means stable and widely used :smile:

**Comment by kmuehlbauer** [comment]
I'm also not sure, if I need that `jpeg` stuff for my use-cases at all. So I'm totally open to all options. If it easy to maintain, I would suggest to leave the decision to the end-user.

There is [this jasper github repo](https://github.com/mdadams/jasper) which has recent activity. Even windows builds are done there.

**Comment by shahramn** [comment]
OpenJPEG v2.x support is added in the ecCodes v2.0.0. See https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
ecCodes is the successor of grib_api and extends support to BUFR as well as GRIB files

**Comment by ocefpaf** [comment]
> There is [this jasper github repo](https://github.com/mdadams/jasper) which has recent activity. Even windows builds are done there.

I had no idea that existed!

Thanks @shahramn. Maybe it is not worth pursing any improvements here and we should focus on maintaining `ecCodes`.

**Comment by kmuehlbauer** [comment]
@shahramn Thanks for the hint. So we can actually try to get both `jasper` and `openjpeg` running with `eccodes`? @ocefpaf Then let's try that there.

**Comment by shahramn** [comment]
Yes please use ecCodes instead of grib_api. Read the migration notes here:
https://software.ecmwf.int/wiki/display/ECC/GRIB-API+migration

Please contact Software.Support@ecmwf.int regarding your contributions. Many thanks

**Comment by ocefpaf** [comment]
> @shahramn Thanks for the hint. So we can actually try to get both jasper and openjpeg running with eccodes? @ocefpaf Then let's try that there.

And Windows :grimacing:

**Comment by kmuehlbauer** [comment]
> Please contact Software.Support@ecmwf.int regarding your contributions. Many thanks

@shahramn It would be good, if we could ping you here on github, if neccessary. Your in-depth knowledge will surely improve `eccodes` builds here on conda-forge.

**Comment by ocefpaf** [comment]
Closing b/c I won't have time to get back to this PR.
